"""Add votes Column

Revision ID: d410ddbbff06
Revises: 42f78bef7689
Create Date: 2026-02-08 12:04:58.060487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd410ddbbff06'
down_revision: Union[str, Sequence[str], None] = '42f78bef7689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.alter_column('post', 'published',
               existing_type=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'true'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'published',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'true'::character varying"))
    op.drop_table('votes')
    # ### end Alembic commands ###
